CXXFLAGS += -nostdlib -m32 -march=i386 -fno-pie -mno-red-zone -ffreestanding -fno-exceptions
LDFLAGS  += -m elf_i386 -z noexecstack

%.onasm: %.asm
	@echo "  NASM $<"
	@nasm -f elf $< -o $@

ifeq ($(CONFIG_ENABLE_FTRACE), y)
CXXFLAGS += -finstrument-functions
endif

ifeq ($(CONFIG_ENABLE_STACKPROTECTOR), y)
CXXFLAGS += -fstack-protector-strong -mstack-protector-guard=global
else
CXXFLAGS += -fno-stack-protector
endif
