obj-$(CONFIG_ENABLE_STACKPROTECTOR) += stackprotector.ocpp

obj-y += generic/cpu.ocpp generic/devices.ocpp
obj-y += archinit.ocpp except.ocpp except.oS sched.oS sched.ocpp

obj-$(CONFIG_PLAIN_BINARY) += startup.oS

obj-y += libgcc.ocpp
