obj-$(CONFIG_ENABLE_STACKPROTECTOR) += stackprotector.o

obj-y += generic/cpu.o generic/devices.o
obj-y += archinit.o except.o except_s.oS sched_s.oS sched.o

obj-$(CONFIG_PLAIN_BINARY) += startup.oS

obj-y += libgcc.o
