obj-$(CONFIG_ENABLE_STACKPROTECTOR) += stackprotector.ocpp

obj-y += generic/cpu.ocpp generic/devices.ocpp generic/memory.ocpp generic/textoutput.ocpp
obj-y += archinit.ocpp memmap.ocpp sched.ocpp sched.oS
obj-y += libgcc.ocpp
