extratargets-y := linker.lds
obj-$(CONFIG_ENABLE_STACKPROTECTOR) += stackprotector.o

obj-d += linux-syscalls monitor abi

obj-y += generic/cpu.o generic/devices.o
obj-y += archinit.o archinit_s.o sched.o paging.o sched_s.o trap.o trap_s.o syscall.o
