#!/usr/bin/python3
import sys
WIDTH = 20

if len(sys.argv) != 2:
    print(f"usage: {sys.argv[0]} name")

print(f"// autogenerated file\n#include <types.h>\n\nuint8_t {sys.argv[1]}[] = {{")
while buf := sys.stdin.buffer.read(WIDTH):
    print("    " + ", ".join([f"0x{c:02x}" for c in buf]) + ",")
    if len(buf) < WIDTH: break
print("};")
