#!/usr/bin/python3
import sys
import binascii
import os

if len(sys.argv) not in range(3, 4):
    print(f"usage: {sys.argv[0]} input output_c [output_h]")

input = open(sys.argv[1], "rb")
output_c = open(sys.argv[2], "w")
output_h = open(os.devnull, "w")
if len(sys.argv) == 4:
    output_h.close()
    output_h = open(sys.argv[3], "w")

input_data = input.read()
input.close()

input_basename = os.path.basename(sys.argv[1])
input_basename = input_basename.replace(".", "_")
input_basename = input_basename.replace("-", "_")

lines_c = []
lines_h = []

lines_c.append(f"// autogenerated file\n\n#include <types.h>\n\nuint8_t file_{input_basename}[{len(input_data)}] = {{\n")
lines_h.append(f"// autogenerated file\n\n#include <types.h>\n\nextern uint8_t file_{input_basename}[{len(input_data)}];")

for line in [input_data[i:i+20] for i in range(0, len(input_data), 20) ]:
    lines_c.append("    ")
    lines_c.append(", ".join([f"0x{byte:02x}" for byte in line]) + ",\n")

lines_c.append("};\n")
output_c.writelines(lines_c)
output_h.writelines(lines_h)

output_c.close()
output_h.close()
