#pragma once
#include <vix/config.h>

/* required */

/* custom */

#define KERNEL_VIRT_ADDRESS CONFIG_KERNEL_HIGHER_HALF
#define KERNEL_PHYS_ADDRESS 0x100000

#define KERNEL_FREE_AREA_BEGIN_OFFSET CONFIG_HHDM_SIZE
#define KERNEL_MEMORY_END_OFFSET      (KERNEL_FREE_AREA_BEGIN_OFFSET + 0x10000000) // KERNEL_FREE_AREA_BEGIN_OFFSET + 256MiB
