#pragma once
#include <vix/config.h>

/* required */

/* custom */

#ifdef CONFIG_ARCH_HAS_PAGING

#define KERNEL_VIRT_ADDRESS CONFIG_KERNEL_HIGHER_HALF
#define KERNEL_PHYS_ADDRESS 0x100000

#define KERNEL_FREE_AREA_BEGIN_OFFSET CONFIG_HHDM_SIZE
#define KERNEL_MEMORY_END_OFFSET      (KERNEL_FREE_AREA_BEGIN_OFFSET + 0x10000000) // KERNEL_FREE_AREA_BEGIN_OFFSET + 256MiB

#else

// this is nonsense, but x86_64 doesn't need it anyway

#define KERNEL_VIRT_ADDRESS 0
#define KERNEL_PHYS_ADDRESS 0x100000

#define KERNEL_FREE_AREA_BEGIN_OFFSET 0
#define KERNEL_MEMORY_END_OFFSET      (KERNEL_FREE_AREA_BEGIN_OFFSET + 0x10000000) // KERNEL_FREE_AREA_BEGIN_OFFSET + 256MiB

#endif
