override INT_CFLAGS += -mlongcalls -mtext-section-literals -fstrict-volatile-bitfields -fno-pie -ffreestanding -nostdinc -nostdlib -nostartfiles -fno-exceptions
override INT_CXXFLAGS += -mlongcalls -mtext-section-literals -fstrict-volatile-bitfields -fno-pie -ffreestanding -nostdinc -nostdlib -nostartfiles -fno-exceptions 
override INT_LDFLAGS  += -nostdlib

ifeq ($(CONFIG_ENABLE_FTRACE), y)
override INT_CFLAGS += -finstrument-functions
override INT_CXXFLAGS += -finstrument-functions
endif

ifeq ($(CONFIG_ENABLE_STACKPROTECTOR), y)
override INT_CFLAGS += -fstack-protector-strong
override INT_CXXFLAGS += -fstack-protector-strong
else
override INT_CFLAGS += -fno-stack-protector
override INT_CXXFLAGS += -fno-stack-protector
endif

ifneq ($(strip $(CONFIG_XTENSA_VARIANT_NAME)),)
override INT_CFLAGS += -I arch/$(BUILD_ARCH)/variants/$(CONFIG_XTENSA_VARIANT_NAME)/include
override INT_CXXFLAGS += -I arch/$(BUILD_ARCH)/variants/$(CONFIG_XTENSA_VARIANT_NAME)/include
endif

ifneq ($(strip $(CONFIG_XTENSA_PLATFORM_NAME)),)
override INT_CFLAGS += -I arch/$(BUILD_ARCH)/platforms/$(CONFIG_XTENSA_PLATFORM_NAME)/include
override INT_CXXFLAGS += -I arch/$(BUILD_ARCH)/platforms/$(CONFIG_XTENSA_PLATFORM_NAME)/include
endif
