obj-$(CONFIG_ENABLE_STACKPROTECTOR) += stackprotector.o

obj-y += generic/cpu.o generic/devices.o
obj-y += archinit.o sched_s.o sched.o io.o

obj-$(CONFIG_XTENSA_TARGET_ESP8266) += vectors.o vectors_s.o
