obj-$(CONFIG_ENABLE_STACKPROTECTOR) += stackprotector.ocpp

obj-y += drivers/uart.ocpp
obj-y += generic/cpu.ocpp generic/devices.ocpp generic/memory.ocpp generic/textoutput.ocpp
obj-y += memmap.ocpp
obj-y += archinit.ocpp 
obj-y += startup.oS
