obj-$(CONFIG_ENABLE_STACKPROTECTOR) += stackprotector.ocpp

obj-d += drivers

obj-y += drivers/uart.ocpp
obj-y += generic/cpu.ocpp generic/devices.ocpp generic/memory.ocpp generic/textoutput.ocpp
obj-y += archinit.ocpp memmap.ocpp exceptions.ocpp
obj-y += startup.oS
