# https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/ARM-Options.html
override CXXFLAGS += -fno-pie -ffreestanding -nostdinc -nostdlib -nostartfiles -fno-exceptions -mno-outline-atomics -march=armv8-a+nofp
override LDFLAGS  += -nostdlib

ifeq ($(CONFIG_ENABLE_FTRACE), y)
override CXXFLAGS += -finstrument-functions
endif

ifeq ($(CONFIG_ENABLE_STACKPROTECTOR), y)
override CXXFLAGS += -fstack-protector-strong -mstack-protector-guard=global
else
override CXXFLAGS += -fno-stack-protector
endif
